# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Download a Build Artifact
      #  uses: actions/download-artifact@v3.0.0
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: refs/tags/llvmorg-14.0.4
        
        
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
         cmake-version: '3.24.2'
         
      - name: setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master
       
      - name: dev-cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
        
      - name : build
        run: |
          mkdir build
          cd build
          set CC=cl    
          set CXX=cl
          cmake -GNinja -DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DLIBCXXABI_USE_LLVM_UNWINDER=YES  ..\llvm  -DCMAKE_BUILD_TYPE=Release
          ninja -w dupbuild=warn
          cd ..
          

      - name: compress
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./build/bin
          outPath: build.tar.gz
      
      - name: compress_
        uses: a7ul/tar-action@v1.1.0
        id: compress1
        with:
          command: c
          files: |
            ./build
          outPath: full_build.tar.gz
          
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin_only
          path: .\build.tar.gz
        
        
      - name: upload-artifact_full
        uses: actions/upload-artifact@v3
        with:
          name: full_build_output
          path: .\full_build.tar.gz
