# This is a basic workflow to help you get started with Actions

name: testign

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: clang-setup
        uses: KyleMayes/install-llvm-action@v1
        with:
         version: "10.0"
      - name : test-clang
        run: |
          mkdir build
          cmake -G Ninja -S runtimes -B build -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -DCMAKE_BUILD_TYPE=Release
          ninja -C build cxx cxxabi unwind 
          
      - name: compress
        run: |
          tar cfJ build.tar.xz ./build
      - name : upload build artifact
        uses: actions/upload-artifact@latest
        with:
          name: libcxx
          path: build.tar.xz
